#!/usr/bin/env bash

# Polybar ------------------------------
# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use 
# polybar-msg cmd quit

# Launch bar1 and bar2
# echo "---" | tee -a $HOME/.log/polybar.log
# polybar main >> $HOME/.log/polybar.log 2>&1 &
# [[ -f ~/.Xresources ]] && xrdb -merge -I $HOME/.Xresources

# echo "Bars launched..."
